# ===================================================================
# 前端服务 - Vue.js + Nginx
# ===================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: vpn-proxy
  labels:
    app: vpn-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpn-frontend
  template:
    metadata:
      labels:
        app: vpn-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: vpn-frontend:latest
        imagePullPolicy: Never  # 使用本地镜像
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      restartPolicy: Always

---
# ===================================================================
# 前端服务 - Service配置
# ===================================================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: vpn-proxy
  labels:
    app: vpn-frontend
    tier: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080  # 通过此端口访问前端
    protocol: TCP
  selector:
    app: vpn-frontend
